---
- block: # Check for nginx.conf

  - name: Check if nginx configuration file is exists
    stat:
      path: "{{ automated_docker_nginx_host_config_file_path }}"
    register: automated_docker_nginx_config_check


- block: # Prepare container

  - name: Install python
    raw: python --version || (apk update && apk add python)
    delegate_to: "{{ automated_docker_run.name }}"
    when: automated_docker_nginx_config_check.stat.exists


- block: # Copy all configuration files to nginx container

  - name: Copy nginx configuration file
    copy:
      src: "{{ automated_docker_host_config_path }}/"
      dest: "{{ automated_docker_nginx_config_path }}/"
    delegate_to: "{{ automated_docker_run.name }}"
    when: automated_docker_nginx_config_check.stat.exists
    notify: Check nginx configuration and reload nginx

  # TODO Backup and revert if check nginx configuration not passes
